DROP PROCEDURE IF EXISTS create_erp_child_accounts;

DELIMITER &&
CREATE PROCEDURE create_erp_child_accounts()
BEGIN    
	INSERT INTO mig_account(
		`External_ID__c`,
		`Type`,
		`RecordTypeId`,
		`annual_revenue__c`,
		`BillingCity`,
		`BillingCountryCode`,
		`BillingPostalCode`,
		`BillingState`,
		`BillingStreet`,
		`Description`,
		`NumberOfEmployees`,
		`Name`,
		`next_renewal_date__c`,
		`phone_alternate__c`,
		`Fax`,
		`Phone`,
		`ShippingCity`,
		`ShippingCountryCode`,
		`ShippingPostalCode`,
		`ShippingState`,
		`ShippingStreet`,
		`Website`,
		`architect__c`,
		`back_orders__c`,
		`central_control_brand__c`,
		-- `Commercial Irrigation Referral Request`,
		-- `Commercial Lighting Referral Request`,
		-- `Contact Frequency`,
		-- `Contact Overdue`,
		`control_system_age__c`,
		`control_system__c`,
		`controller_brand_type__c`,
		`county__c`,
		`course_category__c`,
		`course_opening_year__c`,
		`course_type__c`,
		`customer_marketing_priority__c`,
		`customer_type_category__c`,
		`days_since_last_contact__c`,
		`days_until_hsn_expiration__c`,
		`dealer_number__c`,
		`dist_irrigation_2018__c`,
		`dist_irrigation_2019__c`,
		`dist_lighting_2018__c`,
		`dist_lighting_2019__c`,
		`distibutor_salesman_name__c`,
		`distributor_rep__c`,
		`distributor_salesman_email__c`,
		`dm__c`,
		`expired__c`,
		`facility_id__c`,
		`golf_distributor_billing__c`,
		`golf_holes_type__c`,
		`golf_irrigation_installation__c`,
		`hmds_id__c`,
		`hpp_primary_contact__c`,
		`hpp_primary_contact_email__c`,
		`hpp_secondary_contact__c`,
		`hpp_secondary_contact_email__c`,
		`hsn_expiration_date__c`,
		`hsn_start_date__c`,
		`hunter_golf_customer__c`,
		`hunter_golf_reference__c`,
		`hunter_pilot_course__c`,
		`hunter_preferred_balance__c`,
		`hunter_product__c`,
		`hunter_product_samples__c`,
		`hunter_service_network__c`,
		`hydrawise_customers__c`,
		`hydrawise_id__c`,
		`irrigation_2016__c`,
		`irrigation_2017__c`,
		`irrigation_2018__c`,
		`irrigation_2019__c`,
		`irrigation_design_projects__c`,
		`irrigation_install_projects__c`,
		`last_contact__c`,
		`last_visit_date__c`,
		`level__c`,
		`lighting_2016__c`,
		`lighting_2017__c`,
		`lighting_2018__c`,
		`lighting_2019__c`,
		`mailing_preference__c`,
		`management_company__c`,
		`next_contact_due_date__c`,
		`number_of_holes__c`,
		`number_of_installation_crews__c`,
		`oem__c`,
		`pcp_points_on_hold__c`,
		`pilot_version__c`,
		-- `PO Box City`,
		-- `PO Box Country`,
		-- `PO Box PostalCode`,
		-- `PO Box State`,
		-- `PO Box Address`,
		`points_about_to_expire__c`,
		`preferred_language_list__c`,
		`referral_program__c`,
		`res_irr_ref_req__c`,
		`res_light_ref_req__c`,
		`returned_mail_bad_address__c`,
		`rewards_id__c`,
		`rewards_point_balance__c`,
		`rewards_points_at_risk__c`,
		`rewards_points_earned_monthl__c`,
		`rewards_points_redeemed_mont__c`,
		`rewards_primary_contact__c`,
		`rewards_primary_contact_emai__c`,
		`rotor_age__c`,
		`rotor_brand__c`,
		`rotor_count__c`,
		`rotor_type__c`,
		`sales_reporting_number__c`,
		`services__c`,
		`specialty_list__c`,
		`sso_account_name__c`,
		`year_established__c`,
		`ParentId`
		)
		(
		SELECT 
		a.id,
		a.account_type,
		rt.id, -- record type id
		a.annual_revenue,
		a.billing_address_city,
		vlookup('Country', a.billing_address_country),
		-- case 
		-- 	when a.billing_address_country = 'US' then 'United States' 
		-- 	when a.billing_address_country = 'CA' then 'Canada'
		-- end as billing_address_country,
		#a.billing_address_country,
		a.billing_address_postalcode,
		a.billing_address_state,
		a.billing_address_street,
		a.description,
		a.employees,
		a.name,
		a.next_renewal_date,
		a.phone_alternate,
		a.phone_fax,
		a.phone_office,
		a.shipping_address_city,
		vlookup('Country', a.shipping_address_country),
		-- case 
		-- 	when a.shipping_address_country = 'US' then 'United States' 
		-- 	when a.shipping_address_country = 'CA' then 'Canada'
		-- end as shipping_address_country,
		#a.shipping_address_country,
		a.shipping_address_postalcode,
		a.shipping_address_state,
		a.shipping_address_street,
		a.website,
		ac.architect_c,
		ac.back_orders_c,
		ac.central_control_brand_c,
		-- ac.com_irr_ref_req_c,
		-- ac.com_light_ref_req_c,
		-- ac.contact_frequency_c,
		-- ac.contact_overdue_c,
		ac.control_system_age_c,
		ac.control_system_c,
		ac.controller_brand_type_c,
		ac.county_c,
		ac.course_category_c,
		ac.course_opening_year_c,
		ac.course_type_c,
		ac.customer_marketing_priority_c,
		ac.customer_type_category_c,
		ac.days_since_last_contact_c,
		ac.days_until_hsn_expiration_c,
		ac.dealer_number_c,
		ac.dist_irrigation_2018_c,
		ac.dist_irrigation_2019_c,
		ac.dist_lighting_2018_c,
		ac.dist_lighting_2019_c,
		ac.distibutor_salesman_name_c,
		ac.distributor_rep_c,
		ac.distributor_salesman_email_c,
		ac.dm_c,
		ac.expired_c,
		ac.facility_id_c,
		ac.golf_distributor_billing_c,
		ac.golf_holes_type_c,
		ac.golf_irrigation_installation_c,
		ac.hmds_id_c,
		ac.hpp_primary_contact_c,
		ac.hpp_primary_contact_email_c,
		ac.hpp_secondary_contact_c,
		ac.hpp_secondary_contact_email_c,
		ac.hsn_expiration_date_c,
		ac.hsn_start_date_c,
		ac.hunter_golf_customer_c,
		ac.hunter_golf_reference_c,
		ac.hunter_pilot_course_c,
		ac.hunter_preferred_balance_c,
		ac.hunter_product_c,
		ac.hunter_product_samples_c,
		ac.hunter_service_network_c,
		ac.hydrawise_customers_c,
		ac.hydrawise_id_c,
		ac.irrigation_2016_c,
		ac.irrigation_2017_c,
		ac.irrigation_2018_c,
		ac.irrigation_2019_c,
		ac.irrigation_design_projects_c,
		ac.irrigation_install_projects_c,
		ac.last_contact_c,
		ac.last_visit_date_c,
		ac.level_c,
		ac.lighting_2016_c,
		ac.lighting_2017_c,
		ac.lighting_2018_c,
		ac.lighting_2019_c,
		ac.mailing_preference_c,
		ac.management_company_c,
		case 
			when ac.next_contact_due_date_c = '0000-00-00' then NULL
			else ac.next_contact_due_date_c
		end as next_contact_due_date_c,
		ac.number_of_holes_c,
		ac.number_of_installation_crews_c,
		ac.oem_c,
		ac.pcp_points_on_hold_c,
		ac.pilot_version_c,
		-- ac.po_box_address_city_c,
		-- ac.po_box_address_country_c,
		-- ac.po_box_address_postalcode_c,
		-- ac.po_box_address_state_c,
		-- ac.po_box_address_street_c,
		ac.points_about_to_expire_c,
		ac.preferred_language_list_c,
		ac.referral_program_c,
		ac.res_irr_ref_req_c,
		ac.res_light_ref_req_c,
		ac.returned_mail_bad_address_c,
		ac.rewards_id_c,
		ac.rewards_point_balance_c,
		ac.rewards_points_at_risk_c,
		ac.rewards_points_earned_monthl_c,
		ac.rewards_points_redeemed_mont_c,
		ac.rewards_primary_contact_c,
		ac.rewards_primary_contact_emai_c,
		ac.rotor_age_c,
		ac.rotor_brand_c,
		ac.rotor_count_c,
		ac.rotor_type_c,
		ac.sales_reporting_number_c,
		replace(REPLACE(replace(ac.services_c,' ^','^'),',',';'),'^','') AS services_c,
		replace(REPLACE(replace(ac.specialty_list_c,' ^','^'),',',';'),'^','') AS specialty_list_c,
		ac.sso_account_name_c,
		ac.year_established_c,
		a.parent_id
		FROM hunter.accounts a
		INNER JOIN hunter.accounts_cstm ac ON ac.id_c = a.id
		LEFT OUTER JOIN ref_vlookup sugar_segment ON sugar_segment.vlookup_type = 'SugarCustomerSegment' AND sugar_segment.sugar_type = ac.customer_type_category_c
		LEFT OUTER JOIN ref_customer_segmentation segment_rule ON segment_rule.sugar_customer_segment = sugar_segment.sfdc_type and a.account_type = segment_rule.sugar_customer_type
		LEFT OUTER JOIN ref_record_type rt ON rt.name = segment_rule.sfdc_record_type_name
		WHERE 
		a.deleted = 0
		AND a.parent_id IS NOT NULL
  );
END &&
DELIMITER ;

call create_erp_child_accounts();

select count(*) Children from mig_account where `ParentId` is not null;