DROP TABLE IF EXISTS mig_lead;
CREATE TABLE mig_lead (
    External_ID__c varchar(255) NOT NULL,
    Name varchar(255) NULL,
    Alt_Address_City__c varchar(255) NULL,
    Alt_Address_Country__c varchar(255) NULL,
    Alt_Address_Postal_Code__c varchar(255) NULL,
    Alt_Address_State__c varchar(255) NULL,
    alt_Address_Street__c varchar(255) NULL,
    Birthdate__c varchar(255) NULL,
    Department__c varchar(255) NULL,
    Description text NULL,
    DoNotCall varchar(255) NULL,
    FirstName varchar(255) NULL,
    LastName varchar(255) NULL,
    LeadSource varchar(255) NULL,
    Fax varchar(255) NULL,
    Mobile varchar(255) NULL,
    Phone varchar(255) NULL,
    preferred_language__c varchar(255) NULL,
    City varchar(255) NULL,
    Country varchar(255) NULL,
    PostalCode varchar(255) NULL,
    StateProvince varchar(255) NULL,
    Street varchar(255) NULL,
    Salutation varchar(255) NULL,
    Status varchar(255) NULL,
    status_description__c varchar(255) NULL,
    Title varchar(255) NULL,
    Website varchar(255) NULL,
    specialty_list__c varchar(255) NULL,
    Assigned_To_Date__c varchar(255) NULL,
    res_irr_ref_req__c varchar(255) NULL,
    res_lit_ref_req__c varchar(255) NULL,
    Industry varchar(255) NULL,
    sso_uuid__c varchar(255) NULL,
    sso_log__c varchar(255) NULL,
    hunter_newsletter__c varchar(255) NULL,
    hunter_newsletter_date__c varchar(255) NULL,
    fx_newsletter__c varchar(255) NULL,
    fx_newsletter_date__c varchar(255) NULL,
    hunterompany_news__c varchar(255) NULL,
    hunter_golf_irrigation_email__c varchar(255) NULL,
    hunter_irrigation_emails__c varchar(255) NULL,
    fx_luminaire_lighting_emails__c varchar(255) NULL,
    senninger_agriculture_irriga__c varchar(255) NULL,
    HasOptedOutOfEmail varchar(255) NULL,
	OwnerId char(36) DEFAULT NULL,
	CreatedById char(36) DEFAULT NULL,
	CreatedDate datetime DEFAULT NULL,
    PRIMARY KEY(External_ID__c)
);

INSERT INTO mig_lead (
    External_ID__c,
    Name,
    Alt_Address_City__c,
    Alt_Address_Country__c,
    Alt_Address_Postal_Code__c,
    Alt_Address_State__c,
    alt_Address_Street__c,
    Birthdate__c,
    Department__c,
    Description,
    DoNotCall,
    FirstName,
    LastName,
    LeadSource,
    Fax,
    Mobile,
    Phone,
    preferred_language__c,
    City,
    Country,
    PostalCode,
    StateProvince,
    Street,
    Salutation,
    Status,
    status_description__c,
    Title,
    Website,
    specialty_list__c,
    Assigned_To_Date__c,
    res_irr_ref_req__c,
    res_lit_ref_req__c,
    Industry,
    sso_uuid__c,
    sso_log__c,
    hunter_newsletter__c,
    hunter_newsletter_date__c,
    fx_newsletter__c,
    fx_newsletter_date__c,
    hunterompany_news__c,
    hunter_golf_irrigation_email__c,
    hunter_irrigation_emails__c,
    fx_luminaire_lighting_emails__c,
    senninger_agriculture_irriga__c,
    HasOptedOutOfEmail,
    OwnerId, 
    CreatedById, 
    CreatedDate
) (
    SELECT l.id,
    l.account_name,
    l.alt_address_city,
    l.alt_address_country,
    l.alt_address_postalcode,
    l.alt_address_state,
    l.alt_address_street,
    l.birthdate,
    l.department,
    l.description,
    l.do_not_call,
    l.first_name,
    l.last_name,
    l.lead_source,
    l.phone_fax,
    l.phone_mobile,
    l.phone_work,
    l.preferred_language,
    l.primary_address_city,
    l.primary_address_country,
    l.primary_address_postalcode,
    l.primary_address_state,
    l.primary_address_street,
    l.salutation,
    l.status,
    l.status_description,
    l.title,
    l.website,
    lc.specialtylist_c,
    lc.assigned_to_date_c,
    lc.res_irr_ref_req_c,
    lc.res_lit_ref_req_c,
    lc.customer_type_category_c,
    lc.sso_uuid_c,
    lc.sso_log_c,
    lc.hunter_newsletter_c,
    lc.hunter_newsletter_date_c,
    lc.fx_newsletter_c,
    lc.fx_newsletter_date_c,
    lc.hunter_company_news_c,
    lc.hunter_golf_irrigation_email_c,
    lc.hunter_irrigation_emails_c,
    lc.fx_luminaire_lighting_emails_c,
    lc.senninger_agriculture_irriga_c,
    lc.unsubscribe_all_c,
    owner_user.id,
    creator.id,
    l.date_entered
    FROM hunter.leads l
    INNER JOIN hunter.leads_cstm lc ON lc.id_c = l.id
    LEFT OUTER JOIN ref_users owner_user ON owner_user.sugar_id = l.assigned_user_id
    LEFT OUTER JOIN ref_users creator ON creator.sugar_id = l.created_by
    WHERE l.deleted = 0 AND l.status IN ('New','Assigned')
);

select count(*) from mig_lead;