/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.beckettit.hunter.dm

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new App().greeting

        File f = new File("../../../mappings/Task.sdl")
        println f.absolutePath
        f.eachLine {
            if(!it.startsWith("#")){
                String[] toks = it.split("=")
                println "[name:\"${toks[0]}\", type:\"varchar(255)\", sfdcField: \"${toks[1]}\"],"
                //if(toks[0] != toks[1]) println "${toks[0]} <> ${toks[1]}"
            }
        }
    }
}
