/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.beckettit.hunter.dm.task

import com.beckettit.Env
import com.beckettit.transform.*
import com.beckettit.process.Util
import com.beckettit.salesforce.*
import com.beckettit.salesforce.soap.*
import com.beckettit.jdbc.*
import com.beckettit.hunter.dm.obj.*
import org.apache.log4j.Logger

class DeleteEvents extends BaseTask {

    public DeleteEvents(String[] args){
        super(args)
    }

    public void run() {
        ObjectDef objDef = Event.getExtractObjectDef()
        ObjectDef migObjDef = Event.getInsertMeetingsObjectDef()
        ObjectDef migCallObjDef = Event.getInsertCallsObjectDef()
        jdbc.eachRow("select count(*) c from ${objDef.table} where external_id not in (select external_id__c from ${migObjDef.table}) and external_id not in (select external_id__c from ${migCallObjDef.table})") {
            println it.c
        }

        def ids = []
        jdbc.eachRow("select id from ${objDef.table} where external_id not in (select external_id__c from ${migObjDef.table}) and external_id not in (select external_id__c from ${migCallObjDef.table})") {
            ids << it.id
        }

        println ids

        soap.delete(ids, 25)
    }

    //main task
    static void main(String[] args) {
        DeleteEvents proc = new DeleteEvents(args)
        proc.run()
    }
}
