/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.beckettit.hunter.dm.task

import com.beckettit.Env
import com.beckettit.transform.*
import com.beckettit.process.Util
import com.beckettit.salesforce.*
import com.beckettit.salesforce.soap.*
import com.beckettit.jdbc.*
import com.beckettit.hunter.dm.obj.*
import org.apache.log4j.Logger

class DeleteContacts extends BaseTask {

    public DeleteContacts(String[] args){
        super(args)
    }

    public void run() {
        ObjectDef objDef = Contact.getExtractObjectDef()
        ObjectDef migObjDef = Contact.getInsertObjectDef()
        jdbc.eachRow("select count(*) c from ${objDef.table} where external_id not in (select external_id__c from ${migObjDef.table})") {
            println it.c
        }

        def ids = []
        jdbc.eachRow("select id from ${objDef.table} where external_id not in (select external_id__c from ${migObjDef.table})") {
            ids << it.id
        }

        println ids

        soap.delete(ids, 200)
    }

    //main task
    static void main(String[] args) {
        DeleteContacts proc = new DeleteContacts(args)
        proc.run()
    }
}
