/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.beckettit.hunter.dm.task

import com.beckettit.Env
import com.beckettit.transform.*
import com.beckettit.process.Util
import com.beckettit.salesforce.*
import com.beckettit.salesforce.soap.*
import com.beckettit.jdbc.*
import com.beckettit.hunter.dm.obj.*
import org.apache.log4j.Logger

class ExtractEventRelations extends BaseTask {

    public ExtractEventRelations(String[] args){
        super(args)
    }

    public void run() {
        ObjectDef objDef = EventRelation.getExtractObjectDef()
        Util.extractAll(soap, jdbc, objDef)

        jdbc.execute """
        CREATE INDEX `ref_event_relation_relation_external_id_idx` ON `ref_event_relation` (`relation_external_id`) USING BTREE
        """

        jdbc.execute """
        update ${objDef.table} rer set relation_external_id = (select external_id from ref_contact where id = rer.relation_id)
        """

        jdbc.execute """
        update ${objDef.table} set unique_key = concat(event_external_id, '-', relation_external_id)
        """

        //TODO
        // select * from mig_event_relation where concat(EventId,'-',RelationId) not in (
	    //     select unique_key from ref_event_relation
        // )
    }

    //main task
    static void main(String[] args) {
        ExtractEventRelations proc = new ExtractEventRelations(args)
        proc.run()
    }
}
