/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.beckettit.hunter.dm.task

import com.beckettit.Env
import com.beckettit.transform.*
import com.beckettit.process.Util
import com.beckettit.salesforce.*
import com.beckettit.salesforce.soap.*
import com.beckettit.jdbc.*
import com.beckettit.hunter.dm.obj.*
import org.apache.log4j.Logger

class LoadEventRelations extends BaseTask {
    Boolean insert = false

    public LoadEventRelations(String[] args){
        super(args)
        insert = args?.findAll {
            it == '--insert'
        }.size() > 0
    }

    public void run() {
        if(insert){
            ObjectDef objDef = EventRelation.getInsertObjectDef()
            String query = """
            select * from (
                select ${objDef.getMappedColumnsForQuery('mig')}, c.id ContactId from ${objDef.table} mig
                inner join ref_contact c on c.external_id = mig.RelationId
                left outer join ref_event_relation ref on ref.event_external_id = mig.EventId and ref.relation_external_id = c.external_id 
                where ref.id is null
            ) m
            """
            objDef.mapping.put("ContactId", [name:"ContactId", sfdcField:"RelationId"])
            println query
            soap.upsertAll("insert-event-relations", objDef, query, [batchSize:200])
            Util.backupSaveResults(jdbc, "evtrels")
        }

    }

    //main task
    static void main(String[] args) {
        LoadEventRelations proc = new LoadEventRelations(args)
        proc.run()
    }
}
